- name: QOTD reset all
  hosts: all

  tasks: 
  - name: Reset all services to factory settings
    ansible.builtin.uri:
      url: {{ reset }}
      method: POST
      return_content: yes
      body_format: json
      headers:
        Content-Type: application/json
      body: {}
      status_code: 200
